-- Databricks notebook source
-- MAGIC %md
-- MAGIC ### Example Exploratory Notebook
-- MAGIC
-- MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
-- MAGIC
-- MAGIC **Note**: This notebook is not executed as part of the pipeline.

-- COMMAND ----------

USE CATALOG `adbi_training`;
USE SCHEMA `training`;

-- COMMAND ----------

SELECT * from adbi_training.training.users_raw;

-- COMMAND ----------

select count(*) from adbi_training.training.users_raw;

-- COMMAND ----------

select count(*) from adbi_training.training.users

-- COMMAND ----------

select * from adbi_training.training.users limit 10;

-- COMMAND ----------

select * from adbi_training.training.users_bank limit 10;

-- COMMAND ----------

SELECT u.id, u.first_name, u.last_name, u.email, b.bank_name, b.bank_street_address, b.bank_city, b.bank_country_code
FROM adbi_training.training.users u
JOIN adbi_training.training.users_bank b
  ON u.id = b.id
LIMIT 10;
